name: ElementalKits
main: com.rayzr522.elementalkits.ElementalKits
version: 1.0
description: An elemental kits plugin for Minecraft
author: [Rayzr522,EndureBlackout]
commands:
  ekit:
    description: ElementalKits selector
    usage: "/ekit [kit]"
  elementalkits:
    description: Main ElementalKits command